### YamlMime:ManagedReference
items:
- uid: VoxelPrototype.common.Game.WorldSettings
  commentId: T:VoxelPrototype.common.Game.WorldSettings
  id: WorldSettings
  parent: VoxelPrototype.common.Game
  children:
  - VoxelPrototype.common.Game.WorldSettings.#ctor(System.Int64,System.String,System.String)
  - VoxelPrototype.common.Game.WorldSettings.#ctor(System.String,VoxelPrototype.common.Game.World.WorldInfo)
  - VoxelPrototype.common.Game.WorldSettings.GetGenerator
  - VoxelPrototype.common.Game.WorldSettings.GetName
  - VoxelPrototype.common.Game.WorldSettings.GetSeed
  langs:
  - csharp
  - vb
  name: WorldSettings
  nameWithType: WorldSettings
  fullName: VoxelPrototype.common.Game.WorldSettings
  type: Class
  source:
    remote:
      path: VoxelPrototype/common/Game/WorldSettings.cs
      branch: master
      repo: https://github.com/Bambou72/VoxelPrototype.git
    id: WorldSettings
    path: VoxelPrototype/common/Game/WorldSettings.cs
    startLine: 4
  assemblies:
  - VoxelPrototype
  namespace: VoxelPrototype.common.Game
  syntax:
    content: public class WorldSettings
    content.vb: Public Class WorldSettings
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: VoxelPrototype.common.Game.WorldSettings.GetName
  commentId: M:VoxelPrototype.common.Game.WorldSettings.GetName
  id: GetName
  parent: VoxelPrototype.common.Game.WorldSettings
  langs:
  - csharp
  - vb
  name: GetName()
  nameWithType: WorldSettings.GetName()
  fullName: VoxelPrototype.common.Game.WorldSettings.GetName()
  type: Method
  source:
    remote:
      path: VoxelPrototype/common/Game/WorldSettings.cs
      branch: master
      repo: https://github.com/Bambou72/VoxelPrototype.git
    id: GetName
    path: VoxelPrototype/common/Game/WorldSettings.cs
    startLine: 9
  assemblies:
  - VoxelPrototype
  namespace: VoxelPrototype.common.Game
  syntax:
    content: public string GetName()
    return:
      type: System.String
    content.vb: Public Function GetName() As String
  overload: VoxelPrototype.common.Game.WorldSettings.GetName*
- uid: VoxelPrototype.common.Game.WorldSettings.GetGenerator
  commentId: M:VoxelPrototype.common.Game.WorldSettings.GetGenerator
  id: GetGenerator
  parent: VoxelPrototype.common.Game.WorldSettings
  langs:
  - csharp
  - vb
  name: GetGenerator()
  nameWithType: WorldSettings.GetGenerator()
  fullName: VoxelPrototype.common.Game.WorldSettings.GetGenerator()
  type: Method
  source:
    remote:
      path: VoxelPrototype/common/Game/WorldSettings.cs
      branch: master
      repo: https://github.com/Bambou72/VoxelPrototype.git
    id: GetGenerator
    path: VoxelPrototype/common/Game/WorldSettings.cs
    startLine: 13
  assemblies:
  - VoxelPrototype
  namespace: VoxelPrototype.common.Game
  syntax:
    content: public string GetGenerator()
    return:
      type: System.String
    content.vb: Public Function GetGenerator() As String
  overload: VoxelPrototype.common.Game.WorldSettings.GetGenerator*
- uid: VoxelPrototype.common.Game.WorldSettings.GetSeed
  commentId: M:VoxelPrototype.common.Game.WorldSettings.GetSeed
  id: GetSeed
  parent: VoxelPrototype.common.Game.WorldSettings
  langs:
  - csharp
  - vb
  name: GetSeed()
  nameWithType: WorldSettings.GetSeed()
  fullName: VoxelPrototype.common.Game.WorldSettings.GetSeed()
  type: Method
  source:
    remote:
      path: VoxelPrototype/common/Game/WorldSettings.cs
      branch: master
      repo: https://github.com/Bambou72/VoxelPrototype.git
    id: GetSeed
    path: VoxelPrototype/common/Game/WorldSettings.cs
    startLine: 17
  assemblies:
  - VoxelPrototype
  namespace: VoxelPrototype.common.Game
  syntax:
    content: public long GetSeed()
    return:
      type: System.Int64
    content.vb: Public Function GetSeed() As Long
  overload: VoxelPrototype.common.Game.WorldSettings.GetSeed*
- uid: VoxelPrototype.common.Game.WorldSettings.#ctor(System.Int64,System.String,System.String)
  commentId: M:VoxelPrototype.common.Game.WorldSettings.#ctor(System.Int64,System.String,System.String)
  id: '#ctor(System.Int64,System.String,System.String)'
  parent: VoxelPrototype.common.Game.WorldSettings
  langs:
  - csharp
  - vb
  name: WorldSettings(long, string, string)
  nameWithType: WorldSettings.WorldSettings(long, string, string)
  fullName: VoxelPrototype.common.Game.WorldSettings.WorldSettings(long, string, string)
  type: Constructor
  source:
    remote:
      path: VoxelPrototype/common/Game/WorldSettings.cs
      branch: master
      repo: https://github.com/Bambou72/VoxelPrototype.git
    id: .ctor
    path: VoxelPrototype/common/Game/WorldSettings.cs
    startLine: 21
  assemblies:
  - VoxelPrototype
  namespace: VoxelPrototype.common.Game
  syntax:
    content: public WorldSettings(long Seed, string Generator, string Name)
    parameters:
    - id: Seed
      type: System.Int64
    - id: Generator
      type: System.String
    - id: Name
      type: System.String
    content.vb: Public Sub New(Seed As Long, Generator As String, Name As String)
  overload: VoxelPrototype.common.Game.WorldSettings.#ctor*
  nameWithType.vb: WorldSettings.New(Long, String, String)
  fullName.vb: VoxelPrototype.common.Game.WorldSettings.New(Long, String, String)
  name.vb: New(Long, String, String)
- uid: VoxelPrototype.common.Game.WorldSettings.#ctor(System.String,VoxelPrototype.common.Game.World.WorldInfo)
  commentId: M:VoxelPrototype.common.Game.WorldSettings.#ctor(System.String,VoxelPrototype.common.Game.World.WorldInfo)
  id: '#ctor(System.String,VoxelPrototype.common.Game.World.WorldInfo)'
  parent: VoxelPrototype.common.Game.WorldSettings
  langs:
  - csharp
  - vb
  name: WorldSettings(string, WorldInfo)
  nameWithType: WorldSettings.WorldSettings(string, WorldInfo)
  fullName: VoxelPrototype.common.Game.WorldSettings.WorldSettings(string, VoxelPrototype.common.Game.World.WorldInfo)
  type: Constructor
  source:
    remote:
      path: VoxelPrototype/common/Game/WorldSettings.cs
      branch: master
      repo: https://github.com/Bambou72/VoxelPrototype.git
    id: .ctor
    path: VoxelPrototype/common/Game/WorldSettings.cs
    startLine: 27
  assemblies:
  - VoxelPrototype
  namespace: VoxelPrototype.common.Game
  syntax:
    content: public WorldSettings(string Name, WorldInfo worldInfo)
    parameters:
    - id: Name
      type: System.String
    - id: worldInfo
      type: VoxelPrototype.common.Game.World.WorldInfo
    content.vb: Public Sub New(Name As String, worldInfo As WorldInfo)
  overload: VoxelPrototype.common.Game.WorldSettings.#ctor*
  nameWithType.vb: WorldSettings.New(String, WorldInfo)
  fullName.vb: VoxelPrototype.common.Game.WorldSettings.New(String, VoxelPrototype.common.Game.World.WorldInfo)
  name.vb: New(String, WorldInfo)
references:
- uid: VoxelPrototype.common.Game
  commentId: N:VoxelPrototype.common.Game
  href: VoxelPrototype.html
  name: VoxelPrototype.common.Game
  nameWithType: VoxelPrototype.common.Game
  fullName: VoxelPrototype.common.Game
  spec.csharp:
  - uid: VoxelPrototype
    name: VoxelPrototype
    href: VoxelPrototype.html
  - name: .
  - uid: VoxelPrototype.common
    name: common
    href: VoxelPrototype.common.html
  - name: .
  - uid: VoxelPrototype.common.Game
    name: Game
    href: VoxelPrototype.common.Game.html
  spec.vb:
  - uid: VoxelPrototype
    name: VoxelPrototype
    href: VoxelPrototype.html
  - name: .
  - uid: VoxelPrototype.common
    name: common
    href: VoxelPrototype.common.html
  - name: .
  - uid: VoxelPrototype.common.Game
    name: Game
    href: VoxelPrototype.common.Game.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: VoxelPrototype.common.Game.WorldSettings.GetName*
  commentId: Overload:VoxelPrototype.common.Game.WorldSettings.GetName
  href: VoxelPrototype.common.Game.WorldSettings.html#VoxelPrototype_common_Game_WorldSettings_GetName
  name: GetName
  nameWithType: WorldSettings.GetName
  fullName: VoxelPrototype.common.Game.WorldSettings.GetName
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: VoxelPrototype.common.Game.WorldSettings.GetGenerator*
  commentId: Overload:VoxelPrototype.common.Game.WorldSettings.GetGenerator
  href: VoxelPrototype.common.Game.WorldSettings.html#VoxelPrototype_common_Game_WorldSettings_GetGenerator
  name: GetGenerator
  nameWithType: WorldSettings.GetGenerator
  fullName: VoxelPrototype.common.Game.WorldSettings.GetGenerator
- uid: VoxelPrototype.common.Game.WorldSettings.GetSeed*
  commentId: Overload:VoxelPrototype.common.Game.WorldSettings.GetSeed
  href: VoxelPrototype.common.Game.WorldSettings.html#VoxelPrototype_common_Game_WorldSettings_GetSeed
  name: GetSeed
  nameWithType: WorldSettings.GetSeed
  fullName: VoxelPrototype.common.Game.WorldSettings.GetSeed
- uid: System.Int64
  commentId: T:System.Int64
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.int64
  name: long
  nameWithType: long
  fullName: long
  nameWithType.vb: Long
  fullName.vb: Long
  name.vb: Long
- uid: VoxelPrototype.common.Game.WorldSettings.#ctor*
  commentId: Overload:VoxelPrototype.common.Game.WorldSettings.#ctor
  href: VoxelPrototype.common.Game.WorldSettings.html#VoxelPrototype_common_Game_WorldSettings__ctor_System_Int64_System_String_System_String_
  name: WorldSettings
  nameWithType: WorldSettings.WorldSettings
  fullName: VoxelPrototype.common.Game.WorldSettings.WorldSettings
  nameWithType.vb: WorldSettings.New
  fullName.vb: VoxelPrototype.common.Game.WorldSettings.New
  name.vb: New
- uid: VoxelPrototype.common.Game.World.WorldInfo
  commentId: T:VoxelPrototype.common.Game.World.WorldInfo
  parent: VoxelPrototype.common.Game.World
  href: VoxelPrototype.common.Game.World.WorldInfo.html
  name: WorldInfo
  nameWithType: WorldInfo
  fullName: VoxelPrototype.common.Game.World.WorldInfo
- uid: VoxelPrototype.common.Game.World
  commentId: N:VoxelPrototype.common.Game.World
  href: VoxelPrototype.html
  name: VoxelPrototype.common.Game.World
  nameWithType: VoxelPrototype.common.Game.World
  fullName: VoxelPrototype.common.Game.World
  spec.csharp:
  - uid: VoxelPrototype
    name: VoxelPrototype
    href: VoxelPrototype.html
  - name: .
  - uid: VoxelPrototype.common
    name: common
    href: VoxelPrototype.common.html
  - name: .
  - uid: VoxelPrototype.common.Game
    name: Game
    href: VoxelPrototype.common.Game.html
  - name: .
  - uid: VoxelPrototype.common.Game.World
    name: World
    href: VoxelPrototype.common.Game.World.html
  spec.vb:
  - uid: VoxelPrototype
    name: VoxelPrototype
    href: VoxelPrototype.html
  - name: .
  - uid: VoxelPrototype.common
    name: common
    href: VoxelPrototype.common.html
  - name: .
  - uid: VoxelPrototype.common.Game
    name: Game
    href: VoxelPrototype.common.Game.html
  - name: .
  - uid: VoxelPrototype.common.Game.World
    name: World
    href: VoxelPrototype.common.Game.World.html
